name: baseline
phase: default

target:
  _target_: src.model.trainer_forecast.Trainer
  model:
    type: 'ModelForecast'
    embed_dim: 128
    future_steps: 60
    num_heads: 8
    mlp_ratio: 4.0
    qkv_bias: False
    drop_path: 0.2
  pretrained_weights: ${pretrained_weights}
  lr: ${lr}
  weight_decay: ${weight_decay}
  epochs: ${epochs}
  warmup_epochs: ${warmup_epochs}
