name: av2
phase: default

target:
  _target_: src.datamodule.av2_datamodule.Av2DataModule

  data_root: 'data/DeMo_processed'
  train_batch_size: ${batch_size}
  val_batch_size: ${batch_size}
  test_batch_size: ${batch_size}
  shuffle: True
  num_workers: ${num_workers}
  pin_memory: True
  dataset:
    num_historical_steps: 50
    sequence_origins: [50]
    radius: 150.0
    train_mode: 'only_focal'